<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Version>1.0.0</Version>
    <Product>Axumera License Manager</Product>
    <Company>Axumera Technologies</Company>
    <Copyright>&#169; 2026 Axumera Technologies. All rights reserved.</Copyright>
    <AnalysisLevel>latest</AnalysisLevel>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>